"""Added reward_redeemed column to user table

Revision ID: 84b7b79eb922
Revises: 643d923a85aa
Create Date: 2023-06-24 20:55:19.992086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b7b79eb922'
down_revision = '643d923a85aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_redeemed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stamp_counter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stamp_counter')
        batch_op.drop_column('reward_redeemed')

    with op.batch_alter_table('stamp', schema=None) as batch_op:
        batch_op.drop_column('series')

    # ### end Alembic commands ###
